name: Release taskiq-aio-sqs package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/taskiq-aio-sqs
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        if: steps.setup-uv.outputs.cache-hit != 'true'
        run: make install
      - name: Build dist
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
