name: Testing taskiq-aio-pika

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        cmd:
          - ruff
          - pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: make install
      - name: Run lint check
        run: pre-commit run -a ${{ matrix.cmd }}
  pytest:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install deps
        run: make install
      - name: Run pytest check
        run: make test
      - name: Show Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            thresholdAll: 0.90
            thresholdNew: 0.95
            token: ${{ secrets.GITHUB_TOKEN }}
