name: Testing taskiq-aio-sqs

on:
  pull_request:
      branches:
          - main
          - develop
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

permissions:
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.1"
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: 3.12-python-${{ hashFiles('uv.lock') }}-uv
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make install
      - name: Run typing/linting check
        run: make check
  pytest:
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.py_version }}"
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.1"
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ matrix.py_version }}-python-${{ hashFiles('uv.lock') }}-uv
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make install
      - name: Run pytest check for Python ${{ matrix.py_version }}
        run: make test

